### ISSUE TITLE
libraryPath

### ISSUE THREAD

**Issue by edamderbel** [thoo0224/Gifski.Net#4]
Gifski.Create(@"C:\Test\gifski.dll"

what is this and how can i make I work?

**Comment by thoo0224** [comment]
You need to compile this:

https://github.com/ImageOptim/gifski

**Comment by edamderbel** [comment]
or there is any other solution to use it without that dll file?

**Comment by thoo0224** [comment]
It's a wrapper around gifski's API, so no.
